#!/bin/sh
PID=$1
OPTIONS=$2
PERF_MAP_FILE=/tmp/perf-$PID.map
BASEDIR=$(dirname $0)
PUSER=$(ps -o user -p $PID | sed 1d)

# Make sure only root can run our script
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root/sudo" 1>&2
   exit 1
fi

if [ -p $JAVA_HOME ]; then
  JAVA_HOME=/usr/lib/jvm/default-java
  [ -d $JAVA_HOME ] || JAVA_HOME=/etc/alternatives/java_sdk
fi

cd $BASEDIR
sudo -u $PUSER java -cp $BASEDIR/attach-main.jar:$JAVA_HOME/lib/tools.jar net.virtualvoid.perf.AttachOnce $PID $OPTIONS
chown root:root $PERF_MAP_FILE
perf top -p $PID --objdump=$BASEDIR/jit-objdump.sh
rm $PERF_MAP_FILE
